### ISSUE TITLE
first US

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#1]
## Value Proposition

As a User
I want to see all marvel movies from new to old
So I know which is the latest Marvel movie  
​

## Description

I want to see a headline and then the latest Marvel Movies.
​

## Acceptance Criteria

- [x] on the first page i see a headline and than a list of the all marvel movies from new to old

      ​

## Tasks

- [x] add a heading
- [x] fetch the movies from the Api
- [x] add the logic and show a list of the latest movies
- [x] add the logic to see the movies from new to old      ​

## Complexity

L

**Comment by SarahWett** [comment]
Sounds good & reasonable! :) 
Don't you use wireframes to showcase your idea in your course ? Maybe this would help especially later on when the logic and User Stories get more specific and nested. :)
