### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#10]
## Value Proposition

As a User  
I want to be able to switch the app to dark mode
so that using the app is easier on my eyes
​

## Description

I want to be able to switch the app to dark mode
so that using the app is easier on my eyes. I would like to have an extra settings page for this
​
​

## Acceptance Criteria

- [x] the app switched to the dark mode
- [x] a button on the settings page is displayed to toggle dark mode on and off

      ​

## Tasks

- [x] add the logic for the dark mode
- [x] add the button for dark mode to the settings page
- [x] the dark mode settings are stored in the local storage

      ​

## Complexity

L
