### ISSUE TITLE
Characters on the movie details page

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#14]
## Value Proposition

As a User
I want to see all characters of the Movie
so I can get an overview
​

## Description

the movie details page should display a list of the characters in the movie below
​

## Acceptance Criteria

- [ ] a list of the main characters in the film
      ​

## Tasks

- [ ] Update MongoDB with the characters
- [ ] add a list to the movie details page with the characters
      ​

## Complexity

... (M)
