### ISSUE TITLE
add the nav-bar

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#2]
## Value Proposition

As a User
I want to navigate through the app
so that I can easily navigate through the individual pages of the app
​

## Description

The nav bar should have 3 buttons. Homepage, favorites and settings
​

## Acceptance Criteria

- [x] Three button navigation
- [x] you should be able to see which page you are on
- [x] The navigation bar should be present on all pages
      ​

## Tasks

- [x] create navigation
- [x] Implement the logic to see where you are
- [x] Test the links to the other sites
- [x] add the favorites page
- [x] add the settings page 
      ​

## Complexity

M
