### ISSUE TITLE
Images for the characters

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#21]
## Value Proposition

As a User  
I want to see Images for the characters  
so that i see a image for each character   
​

## Description

the user kann see a image for each character on the details page and the favorite page

![image](https://user-images.githubusercontent.com/122528914/229439507-5770e61c-8f51-43bd-ba3d-63536eb0fc2c.png)

## Acceptance Criteria

- [x] see a pic of the character
- [x] the image has a fixed size
- [x] if there is no image, a placeholder will be displayed​

## Tasks

- [x] fetch the movie data base api
- [x] add a pic of the character to the details page and the favorites
- [x] use the Card component
      ​

## Complexity

... (L)

**Comment by louisweiser** [comment]
you write "i kann see" -> fix this. And i would go with more Acceptance Criteria. For example : The image is not distorted or the size of the image adjusts dynamically, etc. greetings Sascha

**Comment by NinaBusz** [comment]
Hey :wave: Maybe you can add the place where the pictures are shown in the acceptance criteria, as you have written in the description? ("the user kann see a image for each character on the details page and the favorite page") Only thing that comes to my mind - lg! 😄
