### ISSUE TITLE
Backbutton

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#22]
## Value Proposition

As a User 
I would like to be able to press a back button to go to the previous page
so that I can navigate better through the website
​

## Description

On the detail page there should be a button that takes me back to the previous page
​

## Acceptance Criteria

- [ ] a back button in the upper left corner
- [ ] clicking on the button takes you to the previous page
      ​

## Tasks

- [ ] add a BackButton component
- [ ] style the button
- [ ] useRouter router.back
      ​

## Complexity

... (M)

**Comment by louisweiser** [comment]
I like it. As an improvement, I could advise you to make the tasks a bit more detailed, but an experienced developer would have all the information to implement the task.
