### ISSUE TITLE
add a 5 star rating

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#29]
## Value Proposition

As a User  
I want to be rating a movie with a 5 star rating system  
so that i can see what movie i liked and which not
​

## Description

I want to see a 5 star rating system on the movie details page and on the favorites page. My review should be saved for next time.
![image](https://user-images.githubusercontent.com/122528914/230933849-0be04e24-e0c6-4a39-97ba-62816daa28db.png)
​

## Acceptance Criteria

- [ ] 5 star rating is show on the details and favorites page
- [ ] the rating is saved in local storage
- [ ] you can edit the ranking on the details and favorites page
      ​

## Tasks

- [ ] create a Rating Component
- [ ] add the rating to the favorites page
- [ ] add the rating to the details page
- [ ] save the rating to local storage
      ​

## Complexity

... (L)

**Comment by reyk-zepper** [comment]
clear and good to understand👍🏻
