### ISSUE TITLE
add the search bar

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#3]
## Value Proposition

As a User 
I want to be able to search for movies
so I can find the movie I'm looking for faster
​

## Description

I would like a search field in which suggestions for films are made to me after the first word
​
![image](https://user-images.githubusercontent.com/122528914/229438950-f8a687a7-a908-4890-ac54-462b8431a123.png)

## Acceptance Criteria

- [x] after the first word there are suitable suggestions for the search
- [x]  the Search bar is located at the top of the home page
- [x] the movie list is updated with each letter
- [x] if you press enter after typing, the search bar is no longer in focus

## Tasks

- [x] create a search input
- [x] write the logic so that the list is updated after each letter
- [x] adjust the list dynamically

## Complexity

XL

**Comment by louisweiser** [comment]
Very good, maybe a few more details?
