### ISSUE TITLE
Create movie detail page

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#4]
## Value Proposition

As a User
I would like to see an overview of the Movie data
So that I have all the information about a film on one page

## Description

Movie name as a headline then a trailer and the film description.

## Acceptance Criteria

- [x] Overview of the film with title, trailer, description
      ​

## Tasks

- [x] add a heading
- [x] Include trailer
- [x] add the description
- [x] add next routing
      ​

## Complexity

XL

**Comment by reyk-zepper** [comment]
i understand what u want and mean
