### ISSUE TITLE
character detail page

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#5]
## Value Proposition

As a User
I want to see a overview of the character
so I can find out about this movie character
​

## Description

I want the character name as a headline, then there should be a picture and below that the description with a list of the films this character has starred in

## Acceptance Criteria

- [ ] Character as heading
- [ ] a pic from the character
- [ ] the description and a list of the movies
      ​

## Tasks

- [ ] add a heading and the image
- [ ] add the description with the list of movies
- [ ] add links to the movies
      ​

## Complexity

M
