### ISSUE TITLE
add the star to favorite the movie

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#6]
## Value Proposition

As a User
I would like to be able to save films as favorites
so that I can, for example, remember the films I still want to see

## Description

I would like to be able to click on a star on the film details page so that I can remember this film for later
​

## Acceptance Criteria

- [ ] The bookmark should initially have no color and when I click on it it should turn on a color
      ​

## Tasks

- [ ] add Star to the details page
- [ ] write the function to toggle the bookmark
      ​

## Complexity

L
