### ISSUE TITLE
favorite movie page

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#7]
## Value Proposition

As a User  
I want to see a overview of all my favorite Movies  
so I can manage my favorites
​

## Description

A title should be visible on the favorites page and the individual favorites with the film name and picture. You should also be able to toggle the star here.
​

## Acceptance Criteria

- [ ] heading
- [ ] bookmark toggle
- [ ] favorites with heading and pic
- [ ] a list of all favorites 
      ​

## Tasks

- [ ] add the heading
- [ ] add a list of all favorites
- [ ] each favorite has a heading and a pic
      ​

## Complexity

XL
