### ISSUE TITLE
add the setting page

### ISSUE THREAD

**Issue by Sascha-Pionczewski** [Sascha-Pionczewski/Marvel-Movie-App#8]
## Value Proposition

As a User
I would like to be able to adapt the app to my needs
so that I can, for example, use the app in a different language or switch on dark mode

## Description

I would like to be able to change the language of the app on the settings page and switch dark mode on and off
​

## Acceptance Criteria

- [ ] you have to be able to change the language
- [ ] You have to be able to turn dark mode on and off
      ​

## Tasks

- [ ] add a heading
- [ ] add a dropdown to change the language
- [ ] add a toggle button for the dark mode
      ​

## Complexity

M

**Comment by FinjaBaeumcher** [comment]
Maybe you should add this user story to one of the other two so that the user has a real benefit. Because the site itself does not have any real use
